### ISSUE TITLE
Implement new Notion API feature

### ISSUE THREAD

**Issue by ericwang451** [atilatech/client-web-app#10]
Specific [details](https://developers.notion.com/) of this new feature

Render Notion JSON to html using [react-notion](https://github.com/splitbee/react-notion):

Use official Notion API to get JSON -> transform it to the version used by the unofficial API -> render in react-notion

**Comment by ademidun** [comment]
@ericwang451 Please add a short comment explaining why you closed this issue.

Although, I know the reason. It's good to have this documented for our future selves and other people for posterity.

**Comment by ericwang451** [comment]
Meant to create this issue in the ademidun account, which is private.

Not in the open-source/public atilatech account.
